export const mockCategories = [
  { id: 1, name: 'Hot Beverages', description: 'Espresso, cappuccino, latte and more' },
  { id: 2, name: 'Cold Drinks', description: 'Iced drinks, cold brew, smoothies' },
  { id: 3, name: 'Pastries', description: 'Croissants, muffins, cakes' },
  { id: 4, name: 'Light Meals', description: 'Sandwiches, salads, wraps' },
];

export const mockIngredients = [
  { id: 1, name: 'Espresso Beans', unit: 'kg', stock_quantity: 15 },
  { id: 2, name: 'Whole Milk', unit: 'L', stock_quantity: 8 },
  { id: 3, name: 'Oat Milk', unit: 'L', stock_quantity: 5 },
  { id: 4, name: 'Vanilla Syrup', unit: 'bottle', stock_quantity: 3 },
  { id: 5, name: 'Caramel Sauce', unit: 'bottle', stock_quantity: 2 },
  { id: 6, name: 'Cocoa Powder', unit: 'kg', stock_quantity: 1 },
  { id: 7, name: 'Butter', unit: 'kg', stock_quantity: 4 },
  { id: 8, name: 'All-Purpose Flour', unit: 'kg', stock_quantity: 9 },
  { id: 9, name: 'Sugar', unit: 'kg', stock_quantity: 12 },
  { id: 10, name: 'Cream', unit: 'L', stock_quantity: 6 },
];

export const mockMenuItems = [
  {
    id: 1,
    name: 'Signature Espresso',
    description: 'Rich, bold shot of our house-roasted espresso',
    price: 3.5,
    category_id: 1,
    category: 'Hot Beverages',
    image_url: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?w=400',
    status: 'available',
    ingredients: [1],
  },
  {
    id: 2,
    name: 'Creamy Cappuccino',
    description: 'Espresso with steamed milk and thick foam',
    price: 4.5,
    category_id: 1,
    category: 'Hot Beverages',
    image_url: 'https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg?w=400',
    status: 'available',
    ingredients: [1, 2],
  },
  {
    id: 3,
    name: 'Oat Milk Latte',
    description: 'Smooth espresso with creamy oat milk',
    price: 5.0,
    category_id: 1,
    category: 'Hot Beverages',
    image_url: 'https://images.pexels.com/photos/1193335/pexels-photo-1193335.jpeg?w=400',
    status: 'available',
    ingredients: [1, 3],
  },
  {
    id: 4,
    name: 'Vanilla Cold Brew',
    description: '18-hour cold brewed with vanilla',
    price: 5.5,
    category_id: 2,
    category: 'Cold Drinks',
    image_url: 'https://images.pexels.com/photos/3879495/pexels-photo-3879495.jpeg?w=400',
    status: 'available',
    ingredients: [1, 4],
  },
  {
    id: 5,
    name: 'Caramel Iced Latte',
    description: 'Espresso, milk and caramel over ice',
    price: 5.5,
    category_id: 2,
    category: 'Cold Drinks',
    image_url: 'https://images.pexels.com/photos/4051312/pexels-photo-4051312.jpeg?w=400',
    status: 'available',
    ingredients: [1, 2, 5],
  },
  {
    id: 6,
    name: 'Butter Croissant',
    description: 'Flaky, golden butter croissant',
    price: 3.0,
    category_id: 3,
    category: 'Pastries',
    image_url: 'https://images.pexels.com/photos/3010340/pexels-photo-3010340.jpeg?w=400',
    status: 'available',
    ingredients: [7, 8],
  },
  {
    id: 7,
    name: 'Chocolate Muffin',
    description: 'Rich chocolate muffin with cocoa chips',
    price: 3.5,
    category_id: 3,
    category: 'Pastries',
    image_url: 'https://images.pexels.com/photos/1657343/pexels-photo-1657343.jpeg?w=400',
    status: 'available',
    ingredients: [6, 8, 9],
  },
  {
    id: 8,
    name: 'Avocado Toast',
    description: 'Sourdough with smashed avocado and seeds',
    price: 8.5,
    category_id: 4,
    category: 'Light Meals',
    image_url: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?w=400',
    status: 'available',
    ingredients: [7, 8],
  },
];

export const mockTables = [
  { id: 1, number: 1, capacity: 2, status: 'available', qr_code: 'https://api.qrserver.com/v1/create-qr-code/?data=table-1&size=100x100' },
  { id: 2, number: 2, capacity: 4, status: 'occupied', qr_code: 'https://api.qrserver.com/v1/create-qr-code/?data=table-2&size=100x100' },
  { id: 3, number: 3, capacity: 4, status: 'available', qr_code: 'https://api.qrserver.com/v1/create-qr-code/?data=table-3&size=100x100' },
  { id: 4, number: 4, capacity: 6, status: 'occupied', qr_code: 'https://api.qrserver.com/v1/create-qr-code/?data=table-4&size=100x100' },
  { id: 5, number: 5, capacity: 2, status: 'available', qr_code: 'https://api.qrserver.com/v1/create-qr-code/?data=table-5&size=100x100' },
  { id: 6, number: 6, capacity: 8, status: 'available', qr_code: 'https://api.qrserver.com/v1/create-qr-code/?data=table-6&size=100x100' },
];

export const mockOrders = [
  {
    id: 1001,
    table_id: 2,
    table_number: 2,
    items: [
      { menu_item_id: 2, name: 'Creamy Cappuccino', quantity: 2, price: 4.5 },
      { menu_item_id: 6, name: 'Butter Croissant', quantity: 1, price: 3.0 },
    ],
    total: 12.0,
    status: 'preparing',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 1002,
    table_id: 4,
    table_number: 4,
    items: [
      { menu_item_id: 8, name: 'Avocado Toast', quantity: 2, price: 8.5 },
      { menu_item_id: 4, name: 'Vanilla Cold Brew', quantity: 2, price: 5.5 },
    ],
    total: 28.0,
    status: 'ready',
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 1003,
    table_id: 1,
    table_number: 1,
    items: [
      { menu_item_id: 1, name: 'Signature Espresso', quantity: 1, price: 3.5 },
    ],
    total: 3.5,
    status: 'completed',
    created_at: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 1004,
    table_id: 3,
    table_number: 3,
    items: [
      { menu_item_id: 5, name: 'Caramel Iced Latte', quantity: 3, price: 5.5 },
      { menu_item_id: 7, name: 'Chocolate Muffin', quantity: 2, price: 3.5 },
    ],
    total: 23.5,
    status: 'pending',
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
];

const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
export const mockReports = {
  summary: {
    total_revenue: 3842.5,
    total_orders: 218,
    avg_order_value: 17.6,
    top_items: [
      { name: 'Creamy Cappuccino', count: 87 },
      { name: 'Oat Milk Latte', count: 64 },
      { name: 'Avocado Toast', count: 52 },
    ],
  },
  by_category: [
    { category: 'Hot Beverages', revenue: 1620, count: 94 },
    { category: 'Cold Drinks', revenue: 1100, count: 63 },
    { category: 'Pastries', revenue: 620, count: 38 },
    { category: 'Light Meals', revenue: 502.5, count: 23 },
  ],
  trend: days.map((day, i) => ({
    date: day,
    revenue: Math.round(400 + Math.random() * 300 + (i === 5 ? 200 : 0)),
    orders: Math.round(20 + Math.random() * 20 + (i === 5 ? 10 : 0)),
  })),
  inventory: [
    { ingredient_id: 1, name: 'Espresso Beans', stock: 15, threshold: 5, status: 'ok' },
    { ingredient_id: 2, name: 'Whole Milk', stock: 8, threshold: 10, status: 'low' },
    { ingredient_id: 3, name: 'Oat Milk', stock: 5, threshold: 6, status: 'low' },
    { ingredient_id: 4, name: 'Vanilla Syrup', stock: 3, threshold: 4, status: 'critical' },
    { ingredient_id: 5, name: 'Caramel Sauce', stock: 2, threshold: 3, status: 'critical' },
    { ingredient_id: 6, name: 'Cocoa Powder', stock: 1, threshold: 2, status: 'critical' },
    { ingredient_id: 7, name: 'Butter', stock: 4, threshold: 3, status: 'ok' },
    { ingredient_id: 8, name: 'All-Purpose Flour', stock: 9, threshold: 5, status: 'ok' },
  ],
};
